title: TIF1336 Web Framework
description: "Course materials and blog for TIF1336 - Web Framework"
theme: minima

# URL settings
url: "https://dosenjelata.github.io"   # No trailing slash
baseurl: "/tif1336-web-framework"      # Must start with /

# Markdown and permalinks
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag